### ISSUE TITLE
Exception: Expected = after a key. Found ; @ 147563

### ISSUE THREAD

**Issue by gbminnock** [kronenthaler/openstep-parser#10]
Hi, I've newly installed your pbxproj file for manipulating the project.pbxproj file in xcode. 

When I try and load the project I get the following exception which points to an issue with my file. However I haven't edited it yet. 

Can you let me know how to resolve this please? 

Thanks

```
Traceback (most recent call last):
  File "integration.py", line 77, in <module>
    main(sys.argv)
  File "integration.py", line 22, in main
    project = pbxproj.XcodeProject.load(pbxfilename);
  File "build/bdist.macosx-10.12-intel/egg/pbxproj/XcodeProject.py", line 64, in load
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 31, in ParseFromFile
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 35, in ParseFromString
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 44, in _parse
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse_dictionary
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 86, in _parse_dictionary_entry
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 158, in _parse_value
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse_dictionary
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 86, in _parse_dictionary_entry
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 158, in _parse_value
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse_dictionary
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 83, in _parse_dictionary_entry
Exception: Expected = after a key. Found ; @ 147563
```

**Comment by kronenthaler** [comment]
Thanks for your report. Could you attach the project.pbxproj file that is inside your .xcodeproj?

**Comment by gbminnock** [comment]
Hi, 

I figured it out. A third party tool generates out pbxproj file and it had some extras not expected by the openstep_parser. 

I've since found that I can re-use existing project.pbxproj files. So what I do now is open in Xcode and perform all the addition of files and configuration manually - when that is ok I create a backup of the project.pbxproj. I then use that going forward.

For my project I will rarely need to add new files so I think this is an acceptable workaround for now. 

Thank you for your time. 
G

**Comment by kronenthaler** [comment]
Good to hear that you solved your issue. However, it will make the parser better if you could share what exactly was added by those 3rd parties and make the parser aware and handle them gracefully.

**Comment by isairz** [comment]
I have a same issue.

the pbxproj that saved by mod_pbxproj@1.3(save_new_format) couldn't parsed by openstep-parser.
This file is owned by the company, so I can not attach it and I try to make a minimal case.

**Comment by isairz** [comment]
I run xcode and re-save project, the problem is disappear.
