### ISSUE TITLE
Calls to future.standard_library.install_aliases() cause recursion

### ISSUE THREAD

**Issue by markshep** [kronenthaler/openstep-parser#13]
I couldn't get mod-pbxproj working and have tracked it down to being a problem with the calls to `future.standard_library.install_aliases()` in openstep-parser.  Running the following test script:

    print 'import'
    import openstep_parser as osp
    print 'parse'
    tree = osp.OpenStepDecoder.ParseFromFile(open('whatever.pbxproj', 'r'))
    print 'end'

with the stock macOS Python 2.7.10 gives the following output:

    import
    import
    parse
    Traceback (most recent call last):
      File "test.py", line 2, in <module>
        import openstep_parser as osp
      File "/Users/mark/code/recurse/venv/lib/python2.7/site-packages/openstep_parser/__init__.py", line 6, in <module>
        standard_library.install_aliases()
      File "/Users/mark/code/recurse/venv/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
        import test
      File "/Users/mark/code/recurse/test.py", line 5, in <module>
        tree = osp.OpenStepDecoder.ParseFromFile(open('whatever.pbxproj', 'r'))
    AttributeError: 'module' object has no attribute 'OpenStepDecoder'

It looks like it's somehow re-running the test script again and messing up sys.path or something.  Commenting out the two calls to `standard_library.install_aliases()` in `openstep_parser/__init__.py` and `openstep_parser/openstep_parser.py` causes it to work:

    import
    parse
    Traceback (most recent call last):
      File "test.py", line 5, in <module>
        tree = osp.OpenStepDecoder.ParseFromFile(open('whatever.pbxproj', 'r'))
    IOError: [Errno 2] No such file or directory: 'whatever.pbxproj'

Is it safe to just remove those two calls?

**Comment by markshep** [comment]
Ah, the problem is that future.standard_library does an "import test" and as that's the name of my script it imports that instead of whatever it's meant to import.  I'll bug that against future and this can be closed.

**Comment by markshep** [comment]
https://github.com/PythonCharmers/python-future/issues/259
